apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "loki.fullname" . }}-data
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "loki.fullname" . }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ssd
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
